//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFDailyLog.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFDailyLog.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering assist.
        /// </summary>
        internal static string EngineeringAssist {
            get {
                return ResourceManager.GetString("EngineeringAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine PM/Readiness.
        /// </summary>
        internal static string EnginePMReadiness {
            get {
                return ResourceManager.GetString("EnginePMReadiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Staffing.
        /// </summary>
        internal static string ExtendedStaffing {
            get {
                return ResourceManager.GetString("ExtendedStaffing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilities Maintenance.
        /// </summary>
        internal static string FacilitiesMaintenance {
            get {
                return ResourceManager.GetString("FacilitiesMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False Alarm / Cancel.
        /// </summary>
        internal static string FalseAlarmCancel {
            get {
                return ResourceManager.GetString("FalseAlarmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire rehab / Admin.
        /// </summary>
        internal static string FireRehabAdmin {
            get {
                return ResourceManager.GetString("FireRehabAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuels / RX Burning.
        /// </summary>
        internal static string FuelsRXBurning {
            get {
                return ResourceManager.GetString("FuelsRXBurning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GreenFireTruck {
            get {
                object obj = ResourceManager.GetObject("GreenFireTruck", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazmat.
        /// </summary>
        internal static string Hazmat {
            get {
                return ResourceManager.GetString("Hazmat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiring.
        /// </summary>
        internal static string Hiring {
            get {
                return ResourceManager.GetString("Hiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE Assist / S&amp;R.
        /// </summary>
        internal static string LEAssistSR {
            get {
                return ResourceManager.GetString("LEAssistSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ={&quot;A/L&quot;;&quot;S/L&quot;;&quot;Holiday&quot;;&quot;AWOL&quot;;&quot;LWOP&quot;;&quot;Military&quot;;&quot;Admin&quot;}.
        /// </summary>
        internal static string LeaveType {
            get {
                return ResourceManager.GetString("LeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local / Forest cadre.
        /// </summary>
        internal static string LocalForestCadre {
            get {
                return ResourceManager.GetString("LocalForestCadre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MedicalAid.
        /// </summary>
        internal static string MedicalAid {
            get {
                return ResourceManager.GetString("MedicalAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting / Briefing.
        /// </summary>
        internal static string MeetingBriefing {
            get {
                return ResourceManager.GetString("MeetingBriefing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non fire OT.
        /// </summary>
        internal static string NonFireOT {
            get {
                return ResourceManager.GetString("NonFireOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Emergency.
        /// </summary>
        internal static string OtherEmergency {
            get {
                return ResourceManager.GetString("OtherEmergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other hours.
        /// </summary>
        internal static string OtherHours {
            get {
                return ResourceManager.GetString("OtherHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUM(IF(ISNA(MATCH(P7,leaveTypes,0)),0,IF(AB7=&quot;&quot;,BP4,AB7)),IF(ISNA(MATCH(P9,leaveTypes,0)),0,IF(AB9=&quot;&quot;,BP4,AB9)),IF(ISNA(MATCH(P11,leaveTypes,0)),0,IF(AB11=&quot;&quot;,BP4,AB11)),IF(ISNA(MATCH(P13,leaveTypes,0)),0,IF(AB13=&quot;&quot;,BP4,AB13)),IF(ISNA(MATCH(P15,leaveTypes,0)),0,IF(AB15=&quot;&quot;,BP4,AB15)),IF(ISNA(MATCH(P17,leaveTypes,0)),0,IF(AB17=&quot;&quot;,BP4,AB17)),IF(ISNA(MATCH(P19,leaveTypes,0)),0,IF(AB19=&quot;&quot;,BP4,AB19)),IF(ISNA(MATCH(P21,leaveTypes,0)),0,IF(AB21=&quot;&quot;,BP4,AB21)),IF(ISNA(MATCH(P23,leaveTypes,0)),0,IF(AB23=&quot;&quot;,BP4,AB23)),I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OtherHoursFormula {
            get {
                return ResourceManager.GetString("OtherHoursFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overhead Assignments.
        /// </summary>
        internal static string OverheadAssignments {
            get {
                return ResourceManager.GetString("OverheadAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physicals / Drug test.
        /// </summary>
        internal static string PhysicalsDrugTest {
            get {
                return ResourceManager.GetString("PhysicalsDrugTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Training.
        /// </summary>
        internal static string PhysicalTraining {
            get {
                return ResourceManager.GetString("PhysicalTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-suppression.
        /// </summary>
        internal static string PreSuppression {
            get {
                return ResourceManager.GetString("PreSuppression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevention / Patrol.
        /// </summary>
        internal static string PreventionPatrol {
            get {
                return ResourceManager.GetString("PreventionPatrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public assist / Media.
        /// </summary>
        internal static string PublicMedia {
            get {
                return ResourceManager.GetString("PublicMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recreation Assist.
        /// </summary>
        internal static string RecreationAssist {
            get {
                return ResourceManager.GetString("RecreationAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruitment / Outreach.
        /// </summary>
        internal static string RecruitmentOutreach {
            get {
                return ResourceManager.GetString("RecruitmentOutreach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional cadre.
        /// </summary>
        internal static string RegionalCadre {
            get {
                return ResourceManager.GetString("RegionalCadre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional committee.
        /// </summary>
        internal static string RegionalCommittee {
            get {
                return ResourceManager.GetString("RegionalCommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource assist.
        /// </summary>
        internal static string ResourceAssist {
            get {
                return ResourceManager.GetString("ResourceAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety.
        /// </summary>
        internal static string Safety {
            get {
                return ResourceManager.GetString("Safety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        internal static string Severity {
            get {
                return ResourceManager.GetString("Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUM(IF(P7=BQ84,IF(AB7=&quot;&quot;,BP4,AB7),0)+IF(P9=BQ84,IF(AB9=&quot;&quot;,BP4,AB9),0)+IF(P11=BQ84,IF(AB11=&quot;&quot;,BP4,AB11),0)+IF(P13=BQ84,IF(AB13=&quot;&quot;,BP4,AB13),0)+IF(P15=BQ84,IF(AB15=&quot;&quot;,BP4,AB15),0)+IF(P17=BQ84,IF(AB17=&quot;&quot;,BP4,AB17),0)+IF(P19=BQ84,IF(AB19=&quot;&quot;,BP4,AB19),0)+IF(P21=BQ84,IF(AB21=&quot;&quot;,BP4,AB21),0)+IF(P23=BQ84,IF(AB23=&quot;&quot;,BP4,AB23),0)+IF(P25=BQ84,IF(AB25=&quot;&quot;,BP4,AB25),0)).
        /// </summary>
        internal static string SeverityFormula {
            get {
                return ResourceManager.GetString("SeverityFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stand-by / Cover.
        /// </summary>
        internal static string StandByCover {
            get {
                return ResourceManager.GetString("StandByCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Administration.
        /// </summary>
        internal static string StationAdministration {
            get {
                return ResourceManager.GetString("StationAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Maintenance.
        /// </summary>
        internal static string StationMaintenance {
            get {
                return ResourceManager.GetString("StationMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure Fire.
        /// </summary>
        internal static string StructureFire {
            get {
                return ResourceManager.GetString("StructureFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffice Collision.
        /// </summary>
        internal static string TrafficCollision {
            get {
                return ResourceManager.GetString("TrafficCollision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        internal static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Fire.
        /// </summary>
        internal static string VehicleFire {
            get {
                return ResourceManager.GetString("VehicleFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCT(Work Capacity Test).
        /// </summary>
        internal static string WCT {
            get {
                return ResourceManager.GetString("WCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildland Fire Base hours.
        /// </summary>
        internal static string WildlandFireBase {
            get {
                return ResourceManager.GetString("WildlandFireBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildland Fire OT.
        /// </summary>
        internal static string WildlandFireOT {
            get {
                return ResourceManager.GetString("WildlandFireOT", resourceCulture);
            }
        }
    }
}
